# Generated by Django 6.0.6 on 2026-07-05 04:29

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category', models.CharField(choices=[('residential', 'Жилые комплексы'), ('public', 'Общественные здания'), ('cottage', 'Коттеджи, интерьеры и мебель'), ('planning', 'Проекты планировки и градостроительство'), ('design', 'Дизайн-проекты')], default='residential', max_length=20, verbose_name='Категория')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('address', models.CharField(blank=True, help_text='Например: Москва, Крылатские Холмы', max_length=255, verbose_name='Адрес')),
                ('latitude', models.FloatField(default=55.751244, help_text='Координата для 3D-карты', verbose_name='Широта')),
                ('longitude', models.FloatField(default=37.618423, verbose_name='Долгота')),
                ('approximate_location', models.BooleanField(default=False, verbose_name='Координата приблизительная')),
                ('year', models.CharField(blank=True, max_length=32, verbose_name='Год')),
                ('stage', models.CharField(blank=True, help_text='Например: П, РД, ЭП', max_length=64, verbose_name='Стадия')),
                ('customer', models.CharField(blank=True, max_length=128, verbose_name='Заказчик / застройщик')),
                ('lead_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Главное изображение')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='projects.projectpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
