# Generated by Django 6.0.6 on 2026-07-05 04:29

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('icon', models.CharField(choices=[('blueprint', 'Чертёж'), ('lightbulb', 'Концепция'), ('building', 'Здание'), ('frame', 'Конструкции'), ('network', 'Инженерные сети'), ('check', 'Согласование'), ('shield', 'Надзор'), ('palette', 'Дизайн')], default='blueprint', max_length=20, verbose_name='Иконка')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Полное описание')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
