# Generated by Django 6.0.6 on 2026-07-05 04:29

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, default='Институт Проектного Мышления — комплексное проектирование гражданских объектов капитального строительства.', max_length=500, verbose_name='Подзаголовок героя'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, default='Вы принимаете решения — мы создаём возможности', max_length=255, verbose_name='Заголовок героя'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Вступительный текст'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_heading',
            field=models.CharField(blank=True, default='О компании', max_length=255),
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('value', models.CharField(max_length=32, verbose_name='Значение')),
                ('label', models.CharField(max_length=120, verbose_name='Подпись')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
